using System.Reflection;
using System.IO;
using System.CodeDom;
using System.CodeDom.Compiler;
using System.Reflection;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Formatters.Binary;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using Newtonsoft.Json;

namespace SIL.IdlImporterTool;

/// <summary>
/// Generates plain C cdecl API wrapper for Delphi Interfaces
/// </summary>
public class CdeclWrapperGenerator
{
    public ILog? Logger { get; }

    /// <summary>
    /// Directory for temporary files
    /// </summary>
    public readonly string ResultDir;

    /// <summary>
    /// Generates Delphi unit file from IdlImporter result CodeNamespace .JSON
    /// </summary>
    /// <param name="logger">Logger</param>
    /// <param name="resultDir">Folder for temporary files</param>
    public CdeclWrapperGenerator(ILog? logger, string resultDir)
    {
        Logger = logger;
        ResultDir = resultDir;
    }

    /// <summary>
    /// Generates Delphi unit file from IdlImporter result CodeNamespace .JSON
    /// </summary>
    /// <param name="sourceFile">
    /// JSON-serialized CodeDom.CodeNamespace generated by IdlImporter from .idl is required
    /// </param>
    /// <param name="resultUnitName">
    /// Name of generated wrapper unit
    /// Output file is ${resultDir}/${resultUnitName}.pas
    /// </param>
    /// <param name="usesList">
    /// List of units to be added in uses clause
    /// </param>
    public void GenerateFromJson(string sourceFile, string resultUnitName, List<string> usesList)
    {
        // check project file exists
        if (!File.Exists(sourceFile))
            throw new IOException("IdlImporter result CodeNamespace .JSON file not found: " + sourceFile);

        var serializedData = File.ReadAllText(sourceFile);
        var idlNamespace = JsonConvert.DeserializeObject<CodeNamespace>(serializedData,
            new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.Auto });

        GenerateFromCodeNamespace(idlNamespace, resultUnitName, usesList);
    }

    public void GenerateFromCodeNamespace(CodeNamespace idlNamespace, string resultUnitName, List<string> usesList)
    {
        // name of source without extension
        var pasFileName = Path.Join(ResultDir, $"{resultUnitName}.pas");

        Logger?.Message($"Generating Cdecl wrappers file {pasFileName}");

        using (StreamWriter sw = new StreamWriter(pasFileName, append: false))
        {
            GenerateToStream(sw, idlNamespace, resultUnitName, usesList);
        }
    }

    public void GenerateToStream(StreamWriter output, CodeNamespace idlNamespace, string resultUnitName, List<string> usesList)
    {
        var unitsList = string.Join(", ", usesList);
        output.WriteLine($@"unit {resultUnitName};

interface

uses {unitsList};");
        var ifaces = GenerateInterface(output, idlNamespace, resultUnitName, usesList);

        output.WriteLine("implementation");

        GenerateImplementation(output, ifaces);

        output.WriteLine("end.");
    }

    public List<Interface> GenerateInterface(StreamWriter output, CodeNamespace idlNamespace, string resultUnitName, List<string> usesList)
    {
        string ii = "  ";

        var interfaces = new List<Interface>();

        foreach (CodeTypeDeclaration t in idlNamespace.Types)
        {
            if (!t.IsInterface)
            {
                Logger?.Message($"Skipping non-interface type {t.Name}");
                continue;
            }
            Logger?.Message($"Generating Cdecl wrapper for {t.Name}");

            output.WriteLine($@"
type
{ii}{t.Name}_CdeclWrapper = class
{ii}public");

            Interface intf = new(t.Name, new List<Method>());
            foreach (CodeTypeMember member in t.Members)
            {
                if (!(member is CodeMemberMethod method))
                    continue;

                var m = new Method
                {
                    Name = method.Name,
                    Params = new List<ParamDecl>(),
                    ArgsList = new List<string>(),
                    Holders = new Dictionary<string, Holder>(),
                };
                m.Params.Add(new ParamDecl("Self", "Pointer"));
                var usedNames = new Dictionary<string, int>();

                foreach (CodeParameterDeclarationExpression p in method.Parameters)
                {
                    // Not to clash with 'Self' added as the first parameter
                    var pn = MakeName(p.Name, usedNames);
                    var pt = DelphiType(p.Type);
                    m.Params.Add(new ParamDecl(pn, pt));
                    if (p.Direction == FieldDirection.Out)
                    {
                        var ph = MakeHolder(pn, pt, ii, usedNames);
                        m.Holders[pn] = ph;
                        pn = ph.Name;
                    }
                    m.ArgsList.Add(pn);
                }

                var rt = DelphiType(method.ReturnType);

                if (rt != "")
                {
                    var rn = MakeName("Res", usedNames);
                    m.Params.Add(new ParamDecl(rn, rt));
                    var rh = MakeHolder("Res", rt, ii, usedNames);
                    m.Holders[rn] = rh;
                    m.ResPref = $"{rn} := {rt}(";
                    m.ResSuff = ")";
                }

                output.WriteLine($"{ii}{ii}class function Cdecl_{m.Name}({m.ParamDecls()}): Integer; static; cdecl;");
                intf.Methods.Add(m);
            }

            output.WriteLine("end;");
            interfaces.Add(intf);
        }

        output.WriteLine($@"
// WrapAsVTable.Unwrap() is copy/pasted so no deps
function Unwrap(Ptr: Pointer; Pos: Integer = 1): IUnknown;");
        return interfaces;
    }

    public void GenerateImplementation(StreamWriter output, List<Interface> interfaces)
    {
        string ii = "  ";

        foreach (Interface intf in interfaces)
        {
            foreach (Method m in intf.Methods)
            {
                output.WriteLine($@"class function {intf.Name}_CdeclWrapper.Cdecl_{m.Name}({m.ParamDecls()}): Integer; cdecl;");
                if (m.Holders.Count > 0)
                    output.WriteLine("var");
                foreach (Holder h in m.Holders.Values)
                    output.WriteLine($"{ii}{h.Name}: {h.Type};");

                output.WriteLine($@"begin
{ii}{m.ResPref}{intf.Name}(Unwrap(Self)).{m.Name}({m.CallArgs()}){m.ResSuff};
{ii}Result := 0;");

                foreach (Holder h in m.Holders.Values)
                    output.WriteLine(h.Impl);

                output.WriteLine("end;");
            }
        }

        output.WriteLine($@"
function Unwrap(Ptr: Pointer; Pos: Integer): IUnknown;
var
{ii}Loc: PPointer;
begin
{ii}Loc := PPointer(PByte(Ptr) + (Pos * SizeOf(Pointer)));
{ii}Result := IUnknown(Loc^);
end;");
    }

    public record Interface(string Name, List<Method> Methods)
    {}

    public record ParamDecl(string Name, string Type)
    {}

    public record Method
    {
        public string Name  { get; init; }
        public List<ParamDecl> Params  { get; init; }
        public List<string> ArgsList  { get; init; }
        public Dictionary<string, Holder> Holders  { get; init; }
        public string ResPref  { get; set; }
        public string ResSuff  { get; set; }

        public string ParamDecls()
        {
            return string.Join("; ", Params.Select(pd => {
                var op = Holders.ContainsKey(pd.Name) ? "out " : "";
                return $"{op}{pd.Name}: {pd.Type}";
            }));
        }
        public string CallArgs()
        {
            return string.Join(", ", ArgsList);
        }
    }

    public record Holder
    {
        public string Name { get; init; }
        public string Type { get; set; }
        public string Impl { get; set; }
    }

    private static readonly Dictionary<string, string> _delphiTypes = new Dictionary<string, string>
    {
        // TODO: more types
        { "Void", "" },
        { "String", "PWideChar" },
        { "LPCSTR", "PAnsiChar" },
        { "Int32", "Integer" },
        { "IntPtr", "Pointer" },
    };

    private string DelphiType(CodeTypeReference t)
    {
        var key = Regex.Replace(t.BaseType, "^System\\.", "");
        if (_delphiTypes.ContainsKey(key))
            return _delphiTypes[key];
        return t.BaseType;
    }

    private string MakeName(string name, Dictionary<string, int> usedNames)
    {
        if (!usedNames.ContainsKey(name))
        {
            usedNames[name] = 0;
            return name;
        }
        usedNames[name] += 1;
        return $"{name}_{usedNames[name]}";
    }

    private Holder MakeHolder(string name, string type, string ii, Dictionary<string, int> usedNames)
    {
        var holderName = MakeName(name, usedNames);
        var res = new Holder
        {
            Name = holderName,
            Type = type,
            Impl = $"{ii}{name} := {holderName};",
        };
        switch (type)
        {
        // TODO: struct holders?
        case "PWideChar":
            res.Type = "WideString";
            var hold = MakeName("Hold_" + name, usedNames);
            res.Impl = $@"
{ii}var {hold} := TWideStringWrapper.Create({holderName});
{ii}IInterfaceList(Unwrap(Self, 2)).Add({hold});
{ii}{name} := {hold}.Ptr;
";
            break;
        }
        return res;
    }
}
